### PR TITLE
add pvc template

### PR DESCRIPTION
**Pull request by manuelver**
Change the chart to accept pvc template

### CODE REVIEW

**Comment by manuelver** [comment]
@alambike @arvegadev I have tried to ensure that adding the volume does not affect the actual use of the chart.

- I have created pvc and pv.
- I have created all the necessary values to link to EFS.
- I have created values for UID and GID in the volume.

I do not know if it will be necessary to specify permissions for www-data.

**Comment by arvegadev** [comment]
I've been changing some code in the chart, making it simpler and fixing some issues. 

I tried it and it's working. However, to use a PVC we have to take in account some previous steps:

- Create IAM Policy to grant access to the efs-csi-driver to the efs system
- Install EFS-CSI DRIVER

This docs are really useful:  https://docs.aws.amazon.com/es_es/eks/latest/userguide/efs-csi.html

**Comment by arvegadev** [comment]
I think is ready to merge @manuelver , but first we have to take a look to release-please. So talk to me when you want to merge and I'll explain you.

**Review by arvegadev — APPROVED** [review]
LGTM!

**Pull request merged**
